# Generated by Django 5.0.6 on 2024-06-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
