# Generated by Django 5.0.6 on 2024-06-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_shoppingcart_quantity_shippingproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='quantity',
        ),
    ]
