# Generated by Django 5.0.6 on 2024-06-30 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_shoppingcart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoppingcart',
        ),
    ]
